"""Init models

Revision ID: c0bd49bc29b0
Revises: 
Create Date: 2026-06-27 00:11:33.728839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0bd49bc29b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores',
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('manual_cadence', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('chore_id')
    )
    op.create_index(op.f('ix_chores_chore_id'), 'chores', ['chore_id'], unique=False)
    op.create_table('chore_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.chore_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_chore_events_date'), 'chore_events', ['date'], unique=False)
    op.create_index(op.f('ix_chore_events_event_id'), 'chore_events', ['event_id'], unique=False)
    op.create_table('chore_fields',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'float', 'int', 'bool', name='chorefieldtype'), nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.chore_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_index(op.f('ix_chore_fields_field_id'), 'chore_fields', ['field_id'], unique=False)
    op.create_table('chore_event_field_values',
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['chore_events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['chore_fields.field_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('value_id')
    )
    op.create_index(op.f('ix_chore_event_field_values_value_id'), 'chore_event_field_values', ['value_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chore_event_field_values_value_id'), table_name='chore_event_field_values')
    op.drop_table('chore_event_field_values')
    op.drop_index(op.f('ix_chore_fields_field_id'), table_name='chore_fields')
    op.drop_table('chore_fields')
    op.drop_index(op.f('ix_chore_events_event_id'), table_name='chore_events')
    op.drop_index(op.f('ix_chore_events_date'), table_name='chore_events')
    op.drop_table('chore_events')
    op.drop_index(op.f('ix_chores_chore_id'), table_name='chores')
    op.drop_table('chores')
    # ### end Alembic commands ###
