"""Init models

Revision ID: f68113f27c65
Revises: 
Create Date: 2026-10-04 16:09:20.813875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68113f27c65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_log_groups_group_id'), 'log_groups', ['group_id'], unique=False)
    op.create_table('log_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('schedule_rrule', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['log_groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_log_items_group_id'), 'log_items', ['group_id'], unique=False)
    op.create_index(op.f('ix_log_items_item_id'), 'log_items', ['item_id'], unique=False)
    op.create_table('log_entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['log_items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_log_entries_entry_id'), 'log_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_log_entries_item_id'), 'log_entries', ['item_id'], unique=False)
    op.create_index(op.f('ix_log_entries_logged_at'), 'log_entries', ['logged_at'], unique=False)
    op.create_table('log_fields',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['log_items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_index(op.f('ix_log_fields_field_id'), 'log_fields', ['field_id'], unique=False)
    op.create_index(op.f('ix_log_fields_item_id'), 'log_fields', ['item_id'], unique=False)
    op.create_table('log_entry_values',
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['log_entries.entry_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['log_fields.field_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('value_id'),
    sa.UniqueConstraint('entry_id', 'field_id', name='uq_log_entry_field')
    )
    op.create_index(op.f('ix_log_entry_values_entry_id'), 'log_entry_values', ['entry_id'], unique=False)
    op.create_index(op.f('ix_log_entry_values_field_id'), 'log_entry_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_log_entry_values_value_id'), 'log_entry_values', ['value_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entry_values_value_id'), table_name='log_entry_values')
    op.drop_index(op.f('ix_log_entry_values_field_id'), table_name='log_entry_values')
    op.drop_index(op.f('ix_log_entry_values_entry_id'), table_name='log_entry_values')
    op.drop_table('log_entry_values')
    op.drop_index(op.f('ix_log_fields_item_id'), table_name='log_fields')
    op.drop_index(op.f('ix_log_fields_field_id'), table_name='log_fields')
    op.drop_table('log_fields')
    op.drop_index(op.f('ix_log_entries_logged_at'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_item_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_entry_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_log_items_item_id'), table_name='log_items')
    op.drop_index(op.f('ix_log_items_group_id'), table_name='log_items')
    op.drop_table('log_items')
    op.drop_index(op.f('ix_log_groups_group_id'), table_name='log_groups')
    op.drop_table('log_groups')
    # ### end Alembic commands ###
